OPEN_AI:
  API_KEY: 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
  MODEL: 'gpt-3.5-turbo'
  HYPER_TOP_P: 0.5
  HYPER_TEMPERATURE: 0.0
  OPENAI_API_ERROR_LOG: "OPENAPI_ERROR_MSG.log"

NGROK:
  AUTH_KEY: 2NZWXsJX0wihhckEFZ3Xoxd2aQY_4UB7jSz9KnacFjkwKCAEG

DATABASE:
  DB_PREFIX: ChatGee

SETTINGS:
  NO_FRIEND_USE_LIMIT: 7
  ADVERTISEMENT_FREQUENCY: 17
  RESPONSE_SAFE_TIME: 3.4
  SYSTEM_PROMPT: |
          - ChatGee act as an English translator, spelling corrector and improver.
          - ChatGee translate User's prompt into English.
          - ChatGee replace simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences.
          - ChatGee keep the meaning same, but make them more literary.
          - ChatGee only reply the correction, the improvements and nothing else, do not write explanations.
          - ChatGee doens't answer to User's prompt, but just translate the last User's prompt.
          - If User prompt in English, ChatGee now act as an Korean translator.
          - ChatGee doesnt write explanations, but reply only tranlsated texts.
          
CONTENTS:
  SUPPORT_LINK: https://qr.kakaopay.com/Ej87lce5z9c408045

  GREETINGS:
    TITLE: ë§Œë‚˜ì„œ ë°˜ê°‘ìŠµë‹ˆë‹¤! ğŸ¤—ğŸ˜ğŸ‘‹ğŸ‘‹ğŸ‘‹
    TEXTS: |
          ì¹´í†¡ì—ì„œ ChatGPTë¡œ ë²ˆì—­ ğŸ¥³ğŸ‰
          ì–´ëŠ ì–¸ì–´ë“ ì§€ ì˜ì–´ë¡œ ë²ˆì—­í•˜ê³ 
          ë¬¸ì¥ì„ ìˆ˜ì •í•´ ì¤ë‹ˆë‹¤!
          ì˜ì–´ë¥¼ ë„£ìœ¼ì‹œë©´ í•œêµ­ì–´ë¡œ
          ë²ˆì—­í•´ ì¤ë‹ˆë‹¤!

  EXPLAIN:
    TEXTS: |
          ì–´ë–¤ ì–¸ì–´ë“ ì§€ ì˜ì–´ë¡œ ë²ˆì—­!
            â€£ ì˜ì–´ë¡œ ë²ˆì—­í•˜ê³  ë¬¸ì¥ì„ ìˆ˜ì •
            
          ì˜ì–´ë¥¼ ì…ë ¥í•˜ë©´ í•œêµ­ì–´ë¡œ ë²ˆì—­!
            â€£ í•œêµ­ì–´ë¡œ ì…ë ¥í•´ ì¤ë‹ˆë‹¤!
  
  ADVERTISEMENT:
    TEXTS: |
          ë§Œë‚˜ì„œ ë°˜ê°‘ìŠµë‹ˆë‹¤!
          ë§ì€ ê´€ì‹¬ê³¼ ì‚¬ë‘ ë¶€íƒë“œë¦½ë‹ˆë‹¤!
    LINK: mailto:talkchatgpt@email.com

SERVER:
  HOST_NAME: 0.0.0.0
  PORT_NUMBER: 5000
  DEBUG_FLASK: True

